### ISSUE TITLE
Throws Are Bugged

### ISSUE THREAD

**Issue by HammyBoy123** [KyonkoYuuki/YaMovesetOrganizer#2]
The following throws on characters that are broken and need to be fixed

1.Future Gohan
2.Fuu

**Comment by KyonkoYuuki** [comment]
Both of those throws (and we'll throw in Kefla's as well) are more complex then the average throw and require BCM edits, which are out of scope of this tool.  You will need to use YaBCMOrganizer to edit the throw entries and then use YaMoveset to add the rest.
